Repository threeo-clock/WeTube, pull requests merged in 2023-09, with the labels that each got.

#1 mypage 레이아웃 디자인
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/res/drawable/mypage.jpg
  app/src/main/res/layout/fragment_mypage.xml
Labels: enhancement, good first issue

#2 [FEAT] : ⚙️ SearchFragment 더미데이터를 사용해서 gridView 잘 보이는지 확인.
  app/src/main/java/com/example/wetube/Item.kt
  app/src/main/java/com/example/wetube/SearchAdapter.kt
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/res/drawable/img.png
  app/src/main/res/drawable/shape_image.xml
  app/src/main/res/drawable/shape_image2.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_item.xml
Labels: enhancement

#3 [Enhancement][UI] 메인엑티비티 & 홈프레그먼트 레이아웃 작업
  app/build.gradle.kts
  app/src/main/java/com/example/wetube/HomeFragment.kt
  app/src/main/java/com/example/wetube/MainActivity.kt
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/res/drawable/bg_contact_grid.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_channels.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
Labels: enhancement, UI

#4 Feature/retrofit
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/java/com/example/wetube/model/HomeVideos.kt
  app/src/main/java/com/example/wetube/model/SearchVideos.kt
Labels: enhancement

#7 Feature/mypage
  app/build.gradle.kts
  app/src/main/java/com/example/wetube/ItemModel.kt
  app/src/main/java/com/example/wetube/MyPageAdapter.kt
  app/src/main/java/com/example/wetube/MypageFragment.kt
  app/src/main/res/drawable/item_radius.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/item.xml
Labels: enhancement

#9 [FEAT] : ⚙️ [LITTLE_FIX] : 🔧 상세사항 코멘트 참조
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/DetailFragment.kt
  app/src/main/java/com/example/wetube/Item.kt
  app/src/main/java/com/example/wetube/ItemModel.kt
  app/src/main/java/com/example/wetube/MainActivity.kt
  app/src/main/java/com/example/wetube/MyPageAdapter.kt
  app/src/main/java/com/example/wetube/MypageFragment.kt
  app/src/main/java/com/example/wetube/SearchAdapter.kt
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/java/com/example/wetube/model/HomeVideos.kt
  app/src/main/java/com/example/wetube/model/SearchVideos.kt
  app/src/main/java/com/example/wetube/ui/home/Data.kt
  app/src/main/java/com/example/wetube/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/wetube/ui/home/HomeFragment.kt
  app/src/main/res/drawable/bg_contact_grid.xml
  app/src/main/res/drawable/detail_sample.png
  app/src/main/res/drawable/detail_sample2.webp
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_search.xml
  app/src/main/res/drawable/img.png
  app/src/main/res/drawable/item_radius.xml
  app/src/main/res/drawable/mypage.jpg
  app/src/main/res/drawable/shape_image.xml
  app/src/main/res/drawable/shape_image2.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_search_item.xml
  app/src/main/res/layout/item.xml
  app/src/main/res/layout/item_channels.xml
  app/src/main/res/menu/bottom_navigation_menu.xml
  app/src/main/res/navigation/search_nav_graph.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: documentation, enhancement, UI

#10 [FEAT] : ⚙️ SearchFragment 백버튼 추가
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/res/drawable/back_arrow.png
  app/src/main/res/drawable/back_button.xml
  app/src/main/res/layout/fragment_search.xml
Labels: enhancement

#12 ⚙️🐛🔧 상세내용 코멘트 참조
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/res/drawable/detail_sample2.webp
  app/src/main/res/layout/activity_detail.xml
Labels: documentation, enhancement, UI

#13 [Feature | 인기동영상 API로부터 불러오기]
  app/build.gradle.kts
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/DetailFragment.kt
  app/src/main/java/com/example/wetube/api/RetrofitClient.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/java/com/example/wetube/model/HomeVideos.kt
  app/src/main/java/com/example/wetube/model/SearchVideos.kt
  app/src/main/java/com/example/wetube/repository/RepositoryHomeVideos.kt
  app/src/main/java/com/example/wetube/ui/home/HomeAdapter.kt
  app/src/main/java/com/example/wetube/ui/home/HomeFragment.kt
  app/src/main/java/com/example/wetube/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/wetube/viewmodel/HomeViewModelFactory.kt
  app/src/main/res/layout/fragment_detail.xml
  app/src/main/res/navigation/search_nav_graph.xml
Labels: bug, enhancement

#14 [FEAT] : ⚙️ HomeFragment에서 DetailActivity로 data 전달
  app/build.gradle.kts
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/model/HomeVideos.kt
  app/src/main/java/com/example/wetube/ui/home/HomeAdapter.kt
Labels: enhancement

#15 [LITTLE_FIX] : 🔧 DetailActivity layout 수정에 맞춰 intent 변경
  app/src/main/java/com/example/wetube/DetailActivity.kt
Labels: bug
