Repository threeo-clock/WeTube, pull requests merged in 2023-10, with the labels that each got.

#16 [Feat] Search Fragment : Search API 불러오기 완료
  app/src/main/java/com/example/wetube/MainActivity.kt
  app/src/main/java/com/example/wetube/SearchAdapter.kt
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/java/com/example/wetube/model/SearchVideoItems.kt
  app/src/main/java/com/example/wetube/repository/RepositoryHomeVideos.kt
  app/src/main/java/com/example/wetube/ui/home/HomeFragment.kt
  app/src/main/java/com/example/wetube/viewmodel/SearchViewModel.kt
  app/src/main/java/com/example/wetube/viewmodel/SearchViewModelFactory.kt
  app/src/main/res/layout/fragment_search.xml
Labels: bug, enhancement

#18 [FEAT] : ⚙️ SearchFragment API 호출 제한, 검색 결과 없음 등의 예외 상황 (네트워크 오류 처리는 미완)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/java/com/example/wetube/viewmodel/SearchViewModel.kt
Labels: enhancement

#19 [Feature/likes] 좋아요 기능 구현 완료
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/ItemModel.kt
  app/src/main/java/com/example/wetube/LikedVideoPreferences.kt
  app/src/main/java/com/example/wetube/MainActivity.kt
  app/src/main/java/com/example/wetube/MyPageAdapter.kt
  app/src/main/java/com/example/wetube/MypageFragment.kt
  app/src/main/java/com/example/wetube/SearchAdapter.kt
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/java/com/example/wetube/model/HomeVideos.kt
  app/src/main/java/com/example/wetube/ui/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/wetube/ui/mypage/MypageFragment.kt
  app/src/main/java/com/example/wetube/ui/mypage/MypageItem.kt
  app/src/main/java/com/example/wetube/viewmodel/LikesViewModel.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_mypage_favorite_videos.xml
  app/src/main/res/navigation/search_nav_graph.xml
Labels: bug, enhancement

#20 [FEAT] : ⚙️ fragment_search_item.xml 아이템 간격 밑 텍스트 길이 수정
  app/src/main/java/com/example/wetube/SearchAdapter.kt
  app/src/main/res/layout/fragment_search_item.xml
Labels: enhancement

#22 [UI] splash 화면 추가
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/assets/animation_media.json
  app/src/main/java/com/example/wetube/SplashActivity.kt
  app/src/main/res/layout/activity_splash.xml
Labels: UI

#23 [DESIGN] : 🎨 앱 아이콘 추가
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/back_arrow.png
  app/src/main/res/drawable/back_button.xml
  app/src/main/res/drawable/search_button.xml
  app/src/main/res/drawable/searching.png
  app/src/main/res/drawable/searching_click.png
  app/src/main/res/drawable/shape_image.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/mipmap-anydpi-v26/wetube.xml
  app/src/main/res/mipmap-anydpi-v26/wetube_round.xml
  app/src/main/res/mipmap-hdpi/wetube.webp
  app/src/main/res/mipmap-hdpi/wetube_foreground.webp
  app/src/main/res/mipmap-hdpi/wetube_round.webp
  app/src/main/res/mipmap-mdpi/wetube.webp
  app/src/main/res/mipmap-mdpi/wetube_foreground.webp
  app/src/main/res/mipmap-mdpi/wetube_round.webp
  app/src/main/res/mipmap-xhdpi/wetube.webp
  app/src/main/res/mipmap-xhdpi/wetube_foreground.webp
  app/src/main/res/mipmap-xhdpi/wetube_round.webp
  app/src/main/res/mipmap-xxhdpi/wetube.webp
  app/src/main/res/mipmap-xxhdpi/wetube_foreground.webp
  app/src/main/res/mipmap-xxhdpi/wetube_round.webp
  app/src/main/res/mipmap-xxxhdpi/wetube.webp
  app/src/main/res/mipmap-xxxhdpi/wetube_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/wetube_round.webp
  app/src/main/res/values/wetube_background.xml
  app/src/main/wetube-playstore.png
Labels: enhancement

#24 [fix] 공유 intent 띄울 때 url 던지기
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/model/HomeVideos.kt
  app/src/main/java/com/example/wetube/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/wetube/viewmodel/LikesViewModel.kt
  app/src/main/java/com/example/wetube/viewmodel/SearchViewModel.kt
  app/src/main/res/drawable/detail_iv_heart.png
  app/src/main/res/drawable/detail_iv_heart_fill.png
  app/src/main/res/layout/activity_detail.xml
Labels: bug

#25 [FEAT] : ⚙️ SearchAdapter.kt 아이템 클릭시 DetailActivity.kt로 이동
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/SearchAdapter.kt
Labels: enhancement

#26 [FEAT] ⚙️[DESIGN] 🎨 SearchFragment내에서 검색어 입력 전/후 화면 전환 기능 추가
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/res/drawable/image_search.png
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/values/colors.xml
Labels: enhancement

#27 [fix] : MypageFragment 하트색깔 변경 안 되는 것 수정
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/ui/mypage/MypageFragment.kt
  app/src/main/java/com/example/wetube/viewmodel/LikesViewModel.kt
Labels: bug

#28 [fix] : 하트 토글 수정
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/LikedVideoPreferences.kt
  app/src/main/java/com/example/wetube/viewmodel/LikesViewModel.kt
Labels: bug

#29 [FEAT] : ⚙️ SearchFragment.kt 56~69줄
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/res/layout/fragment_search.xml
Labels: enhancement

#30 [FEAT] : ⚙️ SearchFragment.kt 56~69줄
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
Labels: enhancement

#32 Feature/search 22
  .idea/vcs.xml
  app/src/main/java/com/example/wetube/SearchAdapter.kt
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/java/com/example/wetube/repository/RepositoryHomeVideos.kt
  app/src/main/java/com/example/wetube/viewmodel/SearchViewModel.kt
Labels: enhancement

#33 [FEAT] : ⚙️
  app/src/main/java/com/example/wetube/SearchAdapter.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/java/com/example/wetube/viewmodel/SearchViewModel.kt
Labels: enhancement

#34 [FEAT] : ⚙️
  app/src/main/java/com/example/wetube/SearchFragment.kt
  app/src/main/java/com/example/wetube/viewmodel/SearchViewModel.kt
  app/src/main/res/drawable/logowetube.png
Labels: enhancement

#35 [FEAT] : ⚙️ [DESIGN] : 🎨 [LITTLE_FIX] : 🔧
  .idea/deploymentTargetDropDown.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/wetube/DetailActivity.kt
  app/src/main/java/com/example/wetube/Item.kt
  app/src/main/java/com/example/wetube/MainActivity.kt
  app/src/main/java/com/example/wetube/api/YoutubeApi.kt
  app/src/main/java/com/example/wetube/model/HomeVideos.kt
  app/src/main/java/com/example/wetube/repository/RepositoryHomeVideos.kt
  app/src/main/java/com/example/wetube/ui/home/Data.kt
  app/src/main/java/com/example/wetube/ui/home/HomeCategoryAdapter.kt
  app/src/main/java/com/example/wetube/ui/home/HomeChannelAdapter.kt
  app/src/main/java/com/example/wetube/ui/home/HomeFragment.kt
  app/src/main/java/com/example/wetube/ui/home/HomePopularAdapter.kt
  app/src/main/java/com/example/wetube/ui/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/wetube/ui/mypage/MypageFragment.kt
  app/src/main/java/com/example/wetube/ui/search/SearchAdapter.kt
  app/src/main/java/com/example/wetube/ui/search/SearchFragment.kt
  app/src/main/java/com/example/wetube/viewmodel/HomeViewModel.kt
  app/src/main/res/drawable/ic_logo.png
  app/src/main/res/drawable/ic_logo_blue.png
  app/src/main/res/drawable/ic_profile.png
  app/src/main/res/drawable/img_1.png
  app/src/main/res/drawable/logowetube.png
  app/src/main/res/layout-v31/item_video_full.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_mypage.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/item_channels.xml
  app/src/main/res/layout/item_video.xml
  app/src/main/res/layout/item_video_full.xml
  app/src/main/res/navigation/search_nav_graph.xml
Labels: bug, enhancement, UI

#36 [bug fix] mypage RV 수정
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/wetube/LikedVideoPreferences.kt
  app/src/main/java/com/example/wetube/ui/mypage/MyPageAdapter.kt
  app/src/main/java/com/example/wetube/viewmodel/LikesViewModel.kt
  app/src/main/res/layout-v31/item_video_full.xml
Labels: bug

#37 [LITTLE_FIX] : 🔧 디테일 페이지 레이아웃 썸네일 크기 롤백
  app/src/main/res/layout/activity_detail.xml
Labels: UI

#38 [DESIGN] : 🎨 썸네일 이미지 고화질 처리 + 디테일 레이아웃 페이지 이미지 크기 및 위치 수정
  app/src/main/java/com/example/wetube/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/activity_detail.xml
Labels: UI

#41 [MERGE] : ✅ 리드미 작성 & 병합
  README.md
Labels: merge
